# 产品
apiVersion: nautes.resource.nautes.io/v1alpha1
kind: Product
spec:
  name: demo-$suffix
  git:
    gitlab:
      # 产品名称
      name: demo-$suffix
      # 产品路径
      path: demo-$suffix
      visibility: private
      description: demo-$suffix
      parentID: 0
---
# 环境
apiVersion: nautes.resource.nautes.io/v1alpha1
kind: Environment
spec:
  # 环镜名称
  name: env-demo-$suffix
  # 环境的所属产品
  product: demo-$suffix
  # 环境关联的运行时集群
  cluster: $runtime-cluster
  # 环境类型
  envType: dev
---
# 项目
apiVersion: "nautes.resource.nautes.io/v1alpha1"
kind: Project
spec:
  # 项目名称
  name: project-demo-$suffix
  # 项目的所属产品
  product: demo-$suffix
  language: golang
---
# 代码库
apiVersion: nautes.resource.nautes.io/v1alpha1
kind: CodeRepo
spec:
  # 代码库名称
  name: coderepo-demo-$suffix
  codeRepoProvider: gitlab
  deploymentRuntime: true
  pipelineRuntime: false
  # 代码库的所属产品
  product: demo-$suffix
  # 代码库的所属项目
  project: project-demo-$suffix
  webhook:
    events: ["push_events"]
    isolation: shared
  git:
    gitlab:
      # 代码库的名称
      name: coderepo-demo-$suffix
      # 代码库的路径
      path: coderepo-demo-$suffix 
      # 代码库的可见性，例如：private、public
      visibility: private
      description: coderepo-demo-$suffix 
---
# 部署运行时
apiVersion: nautes.resource.nautes.io/v1alpha1
kind: DeploymentRuntime
spec:
  # 部署运行时的名称
  name: dr-demo-$suffix
  # 承载部署运行时的环境
  destination: env-demo-$suffix
  manifestsource:
    # 部署运行时监听的代码库
    codeRepo: coderepo-demo-$suffix
    # 部署运行时监听的代码库的相对路径
    path: deployments/test
    # 部署运行时监听的代码库版本或代码库分支
    targetRevision: main
  # 部署运行时的所属产品
  product: demo-$suffix
  # 部署运行时关联的项目
  projectsRef:
    - project-demo-$suffix