# 宿主集群属性模板
apiVersion: nautes.resource.nautes.io/v1alpha1
kind: Cluster
spec:
  # 集群名称
  name: "host-$suffix"
  # 集群的 API SERVER URL，使用宿主集群的 server 地址替换该变量
  apiServer: "$api-server"
  # 集群种类：目前只支持 kubernetes
  clusterKind: "kubernetes"
  # 集群类型：virtual或physical
  clusterType: "physical"
  # 集群用途：host或worker
  usage: "host"
  # 主域名，使用物理集群的 IP 替换变量 $cluster-ip
  primaryDomain: "$cluster-ip.nip.io"
  # componentsList 可选，集群自定义组件，通过组件的类型选择一个或多个组件安装到集群中
  componentsList:
    gateway:
      name: traefik
      namespace: traefik
      additions:
        httpNodePort: "30080"
        httpsNodePort: "30443"
  # 集群的 kubeconfig 文件内容，使用宿主集群的 kubeconfig 替换该变量
  kubeconfig: |
    $kubeconfig
