# 物理集群属性模板
apiVersion: nautes.resource.nautes.io/v1alpha1
kind: Cluster
spec:
  # 集群名称
  name: "physical-worker-$suffix"
  # 集群的 API SERVER URL。使用物理集群的 server 地址替换该变量
  apiServer: "$api-server"
  # 集群种类：目前只支持 kubernetes
  clusterKind: "kubernetes"
  # 集群类型：virtual或physical
  clusterType: "physical"
  # 集群用途：host或worker
  usage: "worker"
  # 运行时类型：流水线运行时
  workerType: "pipeline"
  # 主域名，使用物理集群的 IP 替换变量 $cluster-ip
  primaryDomain: "$cluster-ip.nip.io"
  # tekton 域名，使用物理集群的 IP 替换变量 $cluster-ip
  tektonHost: "tekton.physical-worker-$suffix.$cluster-ip.nip.io"
  # argocd 域名，使用物理集群的 IP 替换变量 $cluster-ip
  argocdHost: "argocd.physical-worker-$suffix.$cluster-ip.nip.io"
  # traefik 配置
  traefik:
    httpNodePort: "30080"
    httpsNodePort: "30443"
  # componentsList 可选，集群自定义组件
  componentsList:
    multiTenant:
      name: hnc
      namespace: hnc
    certMgt:
      name: cert-manager
      namespace: cert-manager
    secretMgt:
      name: vault
      namespace: vault
    secretSync:
      name: external-secrets
      namespace: external-secrets
    ingressController:
      name: traefik
      namespace: ingress-traefik
    deployment:
      name: argocd
      namespace: argocd
    eventListener:
      name: argo-events
      namespace: argo-events
    pipeline:
      name: tekton
      namespace: tekton-pipelines
  # reservedNamespacesAllowedProducts可选，保留命名空间与产品之间的对应关系，使用产品名称替换：$product-name
  reservedNamespacesAllowedProducts:
    argocd:
      - $product-name
    argo-rollouts:
      - $product-name
    cert-manager:
      - $product-name
    external-secrets:
      - $product-name
    vault:
      - $product-name
  # productAllowedClusterResources可选，产品与集群资源的对应关系，使用产品名称替换：$product-name
  productAllowedClusterResources:
    $product-name:
      - kind: ClusterRole
        group: authorization.k8s.io
      - kind: ClusterRoleBinding
        group: authorization.k8s.io
  # 集群的 kubeconfig 文件内容：使用物理集群的 kubeconfig 替换该变量
  kubeconfig: |
    $kubeconfig
