# 虚拟集群属性模板
apiVersion: nautes.resource.nautes.io/v1alpha1
kind: Cluster
spec:
  # 集群名称
  name: "vcluster-$suffix"
  # 集群的 API SERVER URL，使用 https://$hostcluster-ip:$api-server-port 格式替换参数，其中 $hostcluster-ip 指宿主集群的IP，$api-server-port 指虚拟集群的 API Server 端口
  apiServer: "$api-server"
  # 集群种类：目前只支持 kubernetes
  clusterKind: "kubernetes"
  # 集群类型：virtual或physical
  clusterType: "virtual"
  # 集群用途：host或worker
  usage: "worker"
  # 运行时类型：流水线运行时
  workerType: "pipeline"
  # 所属宿主集群：virtual类型集群才有此属性，使用宿主集群的名称替换参数
  hostCluster: "$host-cluster"
  # 主域名，使用宿主集群的 IP 替换变量 $cluster-ip
  primaryDomain: "$cluster-ip.nip.io"
  # 虚拟集群配置：virtual类型集群才有此属性
  vcluster: 
    # API SERVER 端口号
    httpsNodePort: "$api-server-port"
  # componentsList 可选，集群自定义组件，通过组件的类型选择一个或多个组件安装到集群中
  componentsList:
    multiTenant:
      name: hnc
      namespace: hnc-system
      additions:
        productResourceKustomizeFileFolder: templates/pipelines
        productResourceRevision: main
        syncResourceTypes: tekton.dev/Pipeline
    secretSync:
      name: external-secrets
      namespace: external-secrets
    gateway:
      name: traefik
      namespace: traefik
      # 可选，组件属性
      additions:
        httpNodePort: "30080"
        httpsNodePort: "30443"
    deployment:
      name: argocd
      namespace: argocd
    eventListener:
      name: argo-events
      namespace: argo-events
    pipeline:
      name: tekton
      namespace: tekton-pipelines
  # reservedNamespacesAllowedProducts 可选，如果需要使用组件的保留命名空间，使用产品名称替换：$product-name
  reservedNamespacesAllowedProducts:
    tekton-pipelines:
      - $product-name
    argo-events:
      - $product-name
    argocd:
      - $product-name
    traefik:
      - $product-name
    external-secrets:
      - $product-name
    hnc-system:
      - $product-name
  # productAllowedClusterResources 可选，如果需要使用集群级别的权限，使用产品名称替换：$product-name
  productAllowedClusterResources:
    $product-name:
      - kind: ClusterRole
        group: authorization.k8s.io
      - kind: ClusterRoleBinding
        group: authorization.k8s.io
